# Generated by Django 4.2 on 2023-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.TextField(blank=True),
        ),
    ]
